-- clean

DROP TABLE IF EXISTS public.deposit;
DROP TABLE IF EXISTS public."user";

-- public.deposit definition

CREATE TABLE public.deposit
(
    id_deposit      int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount          int4 NOT NULL,
    date_expiration date NOT NULL,
    date_received   date NOT NULL,
    flag_gift       int4 NOT NULL,
    flag_meal       int4 NOT NULL,
    flag_used       int4 NOT NULL,
    id_receiver     int8 NOT NULL,
    id_sender       int8 NOT NULL,
    CONSTRAINT deposit_pkey PRIMARY KEY (id_deposit)
);

-- public."user" definition

CREATE TABLE public."user"
(
    id_user      int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    flag_company int4 NOT NULL,
    "name"       varchar(255) NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id_user)
);

-- public.deposit foreign keys

ALTER TABLE public.deposit
    ADD CONSTRAINT fk_sender FOREIGN KEY (id_sender) REFERENCES public."user" (id_user);
ALTER TABLE public.deposit
    ADD CONSTRAINT fk_receiver FOREIGN KEY (id_receiver) REFERENCES public."user" (id_user);

INSERT INTO public."user"
    (id_user, flag_company, "name")
VALUES (1, 1, 'Banque_Mondiale'),
       (2, 1, 'Tesla'),
       (3, 0, 'John');

INSERT INTO public.deposit
(amount, date_expiration, date_received, flag_gift, flag_meal, flag_used, id_receiver, id_sender)
--VALUES (1000, '2022-12-31', '2022-01-01', 1, 0, 0, 2, 1);
VALUES (1000, current_date + 700, current_date, 1, 0, 0, 2, 1);
