-- public.deposit definition

CREATE TABLE public.deposit
(
    id_deposit      int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount          int4 NOT NULL,
    date_expiration date NOT NULL,
    date_received   date NOT NULL,
    flag_gift       int4 NOT NULL,
    flag_meal       int4 NOT NULL,
    flag_used       int4 NOT NULL,
    id_receiver     int8 NOT NULL,
    id_sender       int8 NOT NULL,
    CONSTRAINT deposit_pkey PRIMARY KEY (id_deposit)
);

-- public."user" definition

CREATE TABLE public."user"
(
    id_user      int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    flag_company int4 NOT NULL,
    "name"       varchar(255) NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id_user)
);

-- public.deposit foreign keys

ALTER TABLE public.deposit
    ADD CONSTRAINT fk_sender FOREIGN KEY (id_sender) REFERENCES public."user" (id_user);
ALTER TABLE public.deposit
    ADD CONSTRAINT fk_receiver FOREIGN KEY (id_receiver) REFERENCES public."user" (id_user);
